#version: '3.8'

services:
  iot-backend:
    build:
      context: ./backend/api
    container_name: iot-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
      - mosquitto
    networks:
      - iot_network

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - iot_network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - iot_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - iot_network
    depends_on:
      - mosquitto-exporter
      - iot-backend
      - mosquitto
    restart: unless-stopped


  mosquitto-exporter:  # Add Mosquitto Exporter
    image: sapcc/mosquitto-exporter:latest
    platform: linux/amd64
    container_name: mosquitto-exporter
    ports:
      - "9101:9234"
    command:
      - --endpoint=tcp://mosquitto:1883
      - --bind-address=0.0.0.0:9234
    networks:
      - iot_network
    depends_on:
      - mosquitto

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - iot_network

volumes:
  mongo-data:
  grafana-storage:

networks:
  iot_network:
    driver: bridge

