{
 "title": "MQTT Dashboard",
 "tags": [ "mqtt" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MQTT Messages Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mqtt_messages_received_total" }
   ]
  },
  {
   "title": "MongoDB Insert Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mongo_inserts_total" }
   ]
  },
  {
   "title": "HTTP Requests Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  }
 ]
}