apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-api
  labels:
    app: iot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-api
  template:
    metadata:
      labels:
        app: iot-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: iot-api
          image: iot-api # gokselsarikaya/iot-api:latest  # ← Replace
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017"
