global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'iot-backend'
    static_configs:
      - targets: ['iot-backend:3000']

  - job_name: 'mosquitto'
    static_configs:
      - targets: ['mosquitto-exporter:9234']

