global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'iot-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['iot-backend:3000']

  - job_name: 'mosquitto'
    static_configs:
      - targets: ['mosquitto-exporter:9234'] 


# Future configs (uncomment if you add them)
# - job_name: 'mongodb'
#   static_configs:
#     - targets: ['mongodb-exporter:9216']

# - job_name: 'cadvisor'
#   static_configs:
#     - targets: ['cadvisor:8080']